language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install: "pip install -r api/requirements.txt"
# command to run tests
script: python api/server/data_gen.py
script: python api/server/server.py
script: nosetests api/tests/responsetest.py

