language: python
python:
  - "3.4"
addons:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - tox
    - gcc-4.8
    - python-dev
before_install:
  - sudo apt-get -y install python-dev
install: "pip install -r api/requirements.txt"
script:
  - python setup.py build
  - make test

