language: python
python:
  - "2.7"
  - "3.3"
install: "pip install -r api/requirements.txt"
before_script:
  - python api/server/data_gen.py
  - python api/server/server.py&
script:
  - nosetests api/tests/responsetest.py

