language: python
python:
  - "3.4"
addons:
    sources:
      - ubuntu-toolchain-r-testt
    packages:
      - gcc-4.8
      - python-dev
 
install: "pip install -r api/requirements.txt"
before_script:
  - export DB_ENV=testing
script:
  - sudo python setup.py build 
  - behave api/tests/features/

