Items:
  - Iron:
      category: 0
      init_price: 1
      time: 0.0
  - Wood:
      category: 0
      init_price: 1
      time: 0.0
  - Oil:
      category: 0
      init_price: 1
      time: 0.0
  - Water:
      category: 0
      init_price: 1
      time: 0.0
  - Chemicals:
      category: 0
      init_price: 1
      time: 0.0
  - Brinestone:
      category: 0
      init_price: 1
      time: 0.0
  - Salt:
      category: 0
      init_price: 1
      time: 0.0
  - Sulfur:
      category: 0
      init_price: 1
      time: 0.0
  - Coal:
      category: 0
      init_price: 1
      time: 0.0
  - Air:
      category: 0
      time: 0.0
      init_price: 1
  - Sand:
      category: 0
      time: 2.0
      init_price: 1
  - Steel:
      category: 1
      time: 2.0
      init_price: 1
  - Hammer:
      category: 1
      init_price: 1
      time: 2.0
  - Chair:
      category: 1
      init_price: 1
      time: 2.0
  - Planks:
      category: 1
      init_price: 1
      time: 2.0
  - Table:
      category: 1
      init_price: 1
      time: 2.0

Categories:
  - 0:
      desc: "Base goods"
  - 1:
      desc: "Tier one"
  - 2:
      desc: "Tier two"

Blueprint:
  - Table:
      needs:
        Planks: 1
        Steel: 2
        Water: 1
        Hammer: 1
  - Steel:
      needs:
        Water: 1
        Wood: 1
        Iron: 1
        Sulfur: 1
        Sand: 1
  - Hammer:
      needs:
        Steel: 2
        Wood: 3
  - Chair:
      needs:
        Hammer: 1
        Steel: 3
        Wood: 2
  - Planks:
      needs:
        Hammer: 1
        Wood: 2
  
#Effects:
#  - FastProduction:
#      - description: that
#      - name: that
#  - CheaperPrices:
#      - description: that
#      - name: that
#  - SlowerProduction:
#      - description: that
#      - name: that
#  - HigherPrices:
#      - description: that
#      - name: that

Effects:
  - FastProduction
  - CheaperPrices
  - SlowerProduction
  - HigherPrices

Events:
  - Rain 
  - Snow 
  - Wind 

Rain:
  - HigherPrices
  - SlowerProduction

Snow:
  - HigherPrices
  - SlowerProduction

Wind: 
  - HigherPrices
  - SlowerProduction

Technologies:
  - Tech1
  - Tech2
  - Tech3

Tech1:
  - FastProduction
  - CheaperPrices

Tech2:
  - FastProduction
  - CheaperPrices

Tech3:
  - FastProduction
  - CheaperPrices

max_users: 10
